/**
 * Auto Playlist Generator
 * 
 * Автоматическая генерация плейлистов в фоне
 * Аналогично Spotify Daily Mixes
 * 
 * Генерирует:
 * - Daily Mixes (по жанрам/артистам)
 * - Discover Weekly (новинки)
 * - Mood Mixes (по времени суток)
 * - Activity Mixes (для занятий)
 */

import { saveAIGenrePlaylist } from '@/store/generated-playlists.store'
import { analyzeLikedTracksAndCluster, generateGenreClusterPlaylist } from './ai-playlist-generator'
import { useML } from '@/store/ml.store'
import { mlLlmIntegration } from './ml-llm-integration'
import type { ISong } from '@/types/responses/song'

export interface AutoGeneratedPlaylist {
  id: string
  type: 'daily-mix' | 'discover-weekly' | 'mood-mix' | 'activity-mix' | 'genre-mix'
  name: string
  description: string
  songs: ISong[]
  gradient: string
  createdAt: number
  reason: string  // Почему сгенерирован
}

const STORAGE_KEY = 'auto-generated-playlists'

/**
 * Автоматический генератор плейлистов
 */
class AutoPlaylistGenerator {
  private isRunning = false
  private lastGenerationTime = 0
  private readonly GENERATION_INTERVAL = 60 * 60 * 1000  // 1 час

  /**
   * Запуск автоматической генерации
   */
  async start(): Promise<void> {
    if (this.isRunning) {
      console.log('[AutoPlaylist] Already running')
      return
    }

    // Проверяем не слишком ли скоро
    const now = Date.now()
    if (now - this.lastGenerationTime < this.GENERATION_INTERVAL) {
      console.log('[AutoPlaylist] Too soon, skipping')
      return
    }

    this.isRunning = true
    console.log('[AutoPlaylist] Starting auto-generation...')

    try {
      // Инициализируем ML-LLM интеграцию
      mlLlmIntegration.initialize()

      // Генерируем плейлисты
      await this.generateAllPlaylists()

      this.lastGenerationTime = now
      console.log('[AutoPlaylist] Generation complete!')
    } catch (error) {
      console.error('[AutoPlaylist] Error:', error)
    } finally {
      this.isRunning = false
    }
  }

  /**
   * Генерация всех типов плейлистов
   */
  private async generateAllPlaylists(): Promise<void> {
    const state = useML.getState()
    const likedSongIds = state.profile?.likedSongs || []

    if (likedSongIds.length < 10) {
      console.log('[AutoPlaylist] Not enough liked songs')
      return
    }

    // 1. Анализируем жанры
    console.log('[AutoPlaylist] Analyzing genres...')
    const clusters = await analyzeLikedTracksAndCluster(likedSongIds)

    // 2. Генерируем плейлисты для топ-3 жанров
    const topClusters = clusters.slice(0, 3)
    
    for (const cluster of topClusters) {
      try {
        console.log(`[AutoPlaylist] Generating for ${cluster.genre}...`)
        
        // Генерируем с ML-LLM интеграцией
        const playlist = await this.generateWithMLLLM(cluster)
        
        // Сохраняем
        saveAIGenrePlaylist({
          type: 'genre-cluster',
          name: playlist.title,
          description: playlist.description,
          songs: playlist.songs,
          gradient: playlist.gradient,
          genre: cluster.genre,
          metadata: {
            genre: cluster.genre,
            seed: playlist.seed,
            lastTracks: playlist.lastTracks,
          },
        })

        console.log(`[AutoPlaylist] Generated: ${playlist.title}`)
      } catch (error) {
        console.error(`[AutoPlaylist] Failed for ${cluster.genre}:`, error)
      }
    }

    // 3. Генерируем Daily Mix (по времени суток)
    try {
      console.log('[AutoPlaylist] Generating Daily Mix...')
      const dailyMix = await this.generateDailyMix(likedSongIds)
      
      // Сохраняем Daily Mix
      this.saveAutoPlaylist({
        id: 'daily-mix-' + Date.now(),
        type: 'daily-mix',
        name: dailyMix.name,
        description: dailyMix.description,
        songs: dailyMix.songs,
        gradient: dailyMix.gradient,
        createdAt: Date.now(),
        reason: 'Время суток + твои предпочтения',
      })
    } catch (error) {
      console.error('[AutoPlaylist] Daily Mix failed:', error)
    }
  }

  /**
   * Генерация плейлиста с ML-LLM интеграцией
   */
  private async generateWithMLLLM(cluster: any) {
    // Используем mlLlmIntegration для умной генерации
    const playlist = await generateGenreClusterPlaylist(cluster, 30)
    
    // TODO: Интегрировать с mlLlmIntegration.reviewPlaylist
    // Сейчас просто возвращаем сгенерированный плейлист
    
    return playlist
  }

  /**
   * Генерация Daily Mix
   */
  private async generateDailyMix(likedSongIds: string[]) {
    const hour = new Date().getHours()
    const timeOfDay = hour >= 6 && hour < 12 ? 'Утро'
      : hour >= 12 && hour < 18 ? 'День'
      : hour >= 18 && hour < 23 ? 'Вечер'
      : 'Ночь'

    // TODO: Реализовать генерацию по времени суток
    // Сейчас заглушка
    
    return {
      name: `${timeOfDay} микс`,
      description: `Подборка треков для ${timeOfDay.toLowerCase()}`,
      songs: [] as ISong[],
      gradient: 'from-blue-500 to-cyan-500',
    }
  }

  /**
   * Сохранение авто-плейлиста
   */
  private saveAutoPlaylist(playlist: AutoGeneratedPlaylist): void {
    const stored = this.loadPlaylists()
    
    // Добавляем новый в начало
    stored.unshift(playlist)
    
    // Храним максимум 20
    const trimmed = stored.slice(0, 20)
    
    localStorage.setItem(STORAGE_KEY, JSON.stringify(trimmed))
    console.log('[AutoPlaylist] Saved:', playlist.name)
  }

  /**
   * Загрузка авто-плейлистов
   */
  loadPlaylists(): AutoGeneratedPlaylist[] {
    const data = localStorage.getItem(STORAGE_KEY)
    if (!data) return []

    try {
      return JSON.parse(data)
    } catch (error) {
      console.error('[AutoPlaylist] Load failed:', error)
      return []
    }
  }

  /**
   * Получить последние сгенерированные плейлисты
   */
  getRecent(count: number = 10): AutoGeneratedPlaylist[] {
    const stored = this.loadPlaylists()
    return stored.slice(0, count)
  }
}

// Экспортируем единственный экземпляр
export const autoPlaylistGenerator = new AutoPlaylistGenerator()

/**
 * Запуск автоматической генерации при старте приложения
 */
export function initializeAutoPlaylist(): void {
  console.log('[AutoPlaylist] Initializing...')
  
  // Генерируем через 5 секунд после старта
  setTimeout(() => {
    autoPlaylistGenerator.start()
  }, 5000)

  // Затем каждые 2 часа
  setInterval(() => {
    autoPlaylistGenerator.start()
  }, 2 * 60 * 60 * 1000)
}
